add Extra Utilities 2 compat
CleanroomMC/GroovyScript pull request #129
Opened 2024-02-20 16:49 UTC by WaitingIdly

what this PR adds:
- Add compat for the Resonator, Crusher, Enchanter, and Furnace. Featuring returning fan favorites `streamRecipes` and `removeAll`, along with the classic `RecipeBuilder`s. Notably *doesnt* include a `removeByOutput` for most of these.
- Add compat for GP Generators to control the GP scaling, base power tooltip, power multiplier, and the power level function. nightmare to add
- Add compat for the normal power generators. you may think "why wasnt this done in one of these other ways, like we typically do it" and the reason is Extra Utilities 2.
- i18n keys (english) for all of the above
- examples file for the above

wow what an interesting date for the first commit. work very fast over here

2024-03-09 16:37 UTC, brachy84 requested changes

2024-03-09 16:37 UTC, brachy84 commented on src/main/java/com/cleanroommc/groovyscript/compat/mods/extrautils2/Crusher.java
> +    }
I guess we no longer log invalid outputs and if no recipes were found. Thats fine, but we should at least return a boolean if any recipes where removed.

2024-03-09 16:37 UTC, brachy84 commented on src/main/java/com/cleanroommc/groovyscript/compat/mods/extrautils2/GridPowerPassiveGenerator.java
> +    private final Map<ResourceLocation, float[]> scalingMap = new HashMap<>();
`Object2ObjectOpenHashMap`, `Object2FloatOpenHashMap`

2024-03-09 16:37 UTC, brachy84 commented on src/main/java/com/cleanroommc/groovyscript/compat/mods/extrautils2/Resonator.java
> +    }
Why itemstack here and not IIngredient like crusher?

2024-03-09 16:37 UTC, brachy84 commented on src/main/java/com/cleanroommc/groovyscript/compat/mods/extrautils2/Resonator.java
> +    }
what is this 💀

2024-03-10 06:16 UTC, WaitingIdly commented on src/main/java/com/cleanroommc/groovyscript/compat/mods/extrautils2/Resonator.java
> +            this.shouldProgress = ((Closure<Boolean>) new MethodClosure(isRainbowRunning, "run"));
yes, it runs if and only if the Rainbow generator is running.
![image](https://github.com/CleanroomMC/GroovyScript/assets/25394029/d1f53228-76d0-40a3-a133-532714fa589d)

was thinking it was going to be painful before i remembered i could just modify the gens, used this script
```
def cheese() { mods.extrautils2.generator.recipeBuilder().input(item('minecraft:clay')).energy(100000).energyPerTick(1) }

cheese().generator('extrautils2:generator').register()
cheese().generator('extrautils2:generator_survival').register()
cheese().generator('extrautils2:generator_culinary').register()
cheese().generator('extrautils2:generator_potion').register()
cheese().generator('extrautils2:generator_tnt').register()
cheese().generator('extrautils2:generator_pink').register()
cheese().generator('extrautils2:generator_netherstar').register()
cheese().generator('extrautils2:generator_ender').register()
cheese().generator('extrautils2:generator_redstone').fluidInput(fluid('water')).register()
cheese().generator('extrautils2:generator_overclock').register()
cheese().generator('extrautils2:generator_dragonsbreath').register()
cheese().generator('extrautils2:generator_ice').register()
cheese().generator('extrautils2:generator_death').register()
cheese().generator('extrautils2:generator_enchant').register()
cheese().generator('extrautils2:generator_slime').input(item('minecraft:clay')).register()
mods.extrautils2.generator.recipeBuilder().generator('extrautils2:generator_lava').fluidInput(fluid('water')).energy(100000).energyPerTick(1).register()
```

2024-03-11 14:54 UTC, brachy84 requested changes

2024-03-11 14:54 UTC, brachy84 commented on src/main/java/com/cleanroommc/groovyscript/compat/mods/extrautils2/Enchanter.java
> +                        agony.add(recipe);
same

2024-03-17 08:19 UTC, brachy84 requested changes

2024-03-17 08:19 UTC, brachy84 commented on src/main/java/com/cleanroommc/groovyscript/compat/mods/extrautils2/GridPowerPassiveGenerator.java
> +    }
We are not forcing param types on closures. Only log an error in debug mode. Otherwise dont do anything.

2024-03-17 08:19 UTC, brachy84 commented on src/main/java/com/cleanroommc/groovyscript/compat/mods/extrautils2/Resonator.java
> +        }
same here

2024-03-21 15:04 UTC, brachy84 commented
The check still happens without debug mode! The closure should be used regardless of valid signature. But log a message if signature doesnt match in debug mode.

2024-03-22 17:11 UTC, brachy84 approved these changes

2024-03-22 17:12 UTC, merged