add PneumaticCraft: Repressurized compat
CleanroomMC/GroovyScript pull request #162
Opened 2024-05-04 03:06 UTC by WaitingIdly

changes in this PR:
- adds `Amadron`, `AssemblyController`, `Explosion`, `HeatFrameCooling`, `LiquidFuel`, `PlasticMixer`, `PressureChamber`, `Refinery`, `ThermopneumaticProcessingPlant`, and `XpFluid` compat.
- adds examples file and i18n wiki keys for the above compat.
- on the wiki, direct users of the `Explosion` compat towards using the inbuild `inWorldCrafting` explosion compat instead.
- comment out some locations in the `vanilla.groovy` example script that printed out a bunch of lines every reload.
- add types to the Closures in the `loottables.groovy` example script to silence a warning on every reload.

2024-07-03 17:08 UTC, brachy84 requested changes

2024-07-03 22:37 UTC, WaitingIdly commented on src/main/java/com/cleanroommc/groovyscript/compat/mods/pneumaticcraft/PlasticMixer.java
> +        private int meta;
meta is the metadata of the item interacted with.

2024-07-03 22:38 UTC, WaitingIdly commented on src/main/java/com/cleanroommc/groovyscript/compat/mods/pneumaticcraft/PressureChamber.java
> +        }
pressure can be positive or negative in a Pressure Chamber recipe

2024-07-04 07:27 UTC, brachy84 commented on src/main/java/com/cleanroommc/groovyscript/compat/mods/pneumaticcraft/PressureChamber.java
> +        }
cursed

2024-07-05 15:27 UTC, brachy84 approved these changes

2024-07-06 06:03 UTC, merged