Botania Example Script
CleanroomMC/GroovyScript pull request #56
Opened 2023-05-20 23:57 UTC by Testure

Example script for the Botania API.

Also fixes a warning in `ElvenTrade`.

2023-05-31 08:26 UTC, brachy84 requested changes

2023-05-31 08:26 UTC, brachy84 commented on src/main/java/com/cleanroommc/groovyscript/compat/mods/botania/ElvenTrade.java
> +                .add("could not find recipe with outputs {}", (Object[]) outputs)
Arrays are not properly converted to string. Use `Arrays.toString(outputs)`.

2023-06-20 07:07 UTC, WaitingIdly requested changes

2023-06-20 07:07 UTC, WaitingIdly commented on examples/botania.groovy
belatedly: all of our docs include single quotes (`'`) for strings. this should be changed to also be the case here

2023-06-20 07:29 UTC, WaitingIdly approved these changes

2023-06-23 15:38 UTC, brachy84 commented on examples/botania.groovy
You can make a PR to change all of them if you want. I did it because i think it looks nicer.

2023-06-23 15:39 UTC, brachy84 approved these changes

2023-06-24 19:02 UTC, merged