Forestry support
CleanroomMC/GroovyScript pull request #57
Opened 2023-05-21 00:05 UTC by Testure

Includes support for all machines (except bottler because bottler is schizophrenic) plus bee mutations and bee products.

2023-06-13 08:36 UTC, WaitingIdly requested changes
- noted down a bunch of non-validated variables that look like they should be validated (eg via `msg.add(time < 0, "time must be a nonnegative integer, yet it was {}", time);`)
- can you add an examples script so these changes can be easily tested?

2023-06-13 08:36 UTC, WaitingIdly commented on src/main/java/com/cleanroommc/groovyscript/compat/mods/forestry/Centrifuge.java
> +        protected Map<ItemStack, Float> outputs = new Object2FloatOpenHashMap<>();
neither `time` nor `outputs` is validated

2023-06-13 08:36 UTC, WaitingIdly commented on src/main/java/com/cleanroommc/groovyscript/compat/mods/forestry/Centrifuge.java
> +        public AbstractRecipeBuilder<ICentrifugeRecipe> output(ItemStack output) {
why does this use `AbstractRecipeBuilder<ICentrifugeRecipe>` instead of `RecipeBuilder`?

2023-06-13 08:36 UTC, WaitingIdly commented on src/main/java/com/cleanroommc/groovyscript/compat/mods/forestry/Squeezer.java
> +        protected float chance = 1.0F;
neither `time` nor `chance` are validated

2023-06-13 20:49 UTC, Testure commented on src/main/java/com/cleanroommc/groovyscript/compat/mods/forestry/Forestry.java
> +        addRegistry(beeMutations);
Sadly mod support registries happen before Forestry's modules.

2023-06-13 20:52 UTC, Testure commented on src/main/java/com/cleanroommc/groovyscript/brackets/SpeciesBracketHandler.java
> +        return "species" + capital;
I now only do the name conversion after the name you actually entered fails. (Regardless of if it's a forestry id or not)

2023-06-15 09:37 UTC, WaitingIdly requested changes

2023-06-15 09:37 UTC, WaitingIdly commented on src/main/java/com/cleanroommc/groovyscript/compat/mods/forestry/Carpenter.java
> +    @Override
line break

2023-06-15 09:37 UTC, WaitingIdly commented on src/main/java/com/cleanroommc/groovyscript/compat/mods/forestry/Centrifuge.java
> +            msg.add(outputs.isEmpty(), "Expected at least 1 output! got 0.");
cant have more outputs than 9

2023-06-20 07:05 UTC, WaitingIdly approved these changes

2023-06-23 15:37 UTC, brachy84 approved these changes

2023-06-23 15:37 UTC, brachy84 commented on src/main/java/com/cleanroommc/groovyscript/compat/mods/forestry/Forestry.java
> +        addRegistry(beeMutations);
Ill probably add a late init method that will run before post init to make this possible.

2023-06-23 15:37 UTC, brachy84 commented on src/main/java/com/cleanroommc/groovyscript/core/mixin/forestry/BeeRootAccessor.java
> +    @Accessor
Keeping an empty line after the class name looks nicer.

2023-06-24 19:06 UTC, brachy84 approved these changes

2023-06-24 19:06 UTC, merged