Add String based alternatives to builders that use Aspects
CleanroomMC/GroovyScript pull request #60
Opened 2023-06-18 21:44 UTC by Testure

Allows you to use `.aspect("aer", 5)` instead of `.aspect(aspect("aer") * 5)` for convenience.

2023-06-18 23:59 UTC, WaitingIdly requested changes
could you add these new options to the example file?

2023-06-19 12:07 UTC, WaitingIdly approved these changes

2023-06-23 15:17 UTC, brachy84 requested changes
Unlike the aspect bracket handler, this doesnt do any validation if the aspect really exists.

2023-06-24 08:46 UTC, brachy84 commented
Now you completely changed the aspect bracket handler. An exception should only be thrown if there's an invalid amount of arguments or if the arguments have the wrong type. Otherwise it should return null. The bracket handler will then automatically handle the error message.

2023-06-24 10:48 UTC, brachy84 approved these changes

2023-06-24 19:03 UTC, merged